############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "A propos"
url = "/about"
weight = 3

[[main]]
name = "Les piliers"
url = "/piliers"
weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 4


# footer menu
[[footer]]
name = "A propos"
url = "/about"
weight = 1

[[footer]]
name = "Politique de Confidentialité"
url = "/privacy-policy"
weight = 3
