############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "/about"
weight = 2

[[main]]
name = "Mon approche"
url = "/piliers"
weight = 3

# footer menu
[[footer]]
name = "À propos"
url = "/about"
weight = 1

[[footer]]
name = "Mon approche"
url = "/piliers"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3

[[footer]]
name = "Politique de confidentialité"
url = "/privacy-policy"
weight = 4
